pub mod auth;
pub mod collection_domain;
pub mod config;
pub mod config_domain;
pub mod errors;
pub mod file_ownership;
pub mod folder_registry;
pub mod idempotency;
pub mod loop_domain;
pub mod loop_side_effects;
pub mod loop_support;
pub mod mcp;
pub mod planning_domain;
pub mod preset_domain;
pub mod protocol;
pub mod runtime;
pub mod stream_domain;
pub mod supervisor;
pub mod task_domain;
pub mod transport;
pub mod worker_domain;

pub use config::{ApiConfig, AuthMode};
pub use folder_registry::FolderRegistry;
pub use mcp::serve_stdio;
pub use runtime::RpcRuntime;
pub use transport::{router, router_with_registry, serve, serve_registry, serve_with_listener};
