# ABOUTME: Agnostic validation gate framework for ralph-orchestrator
# ABOUTME: Provides abstract validation gates that work with any testing methodology

"""
Agnostic Validation Gate Framework.

This module provides a framework-agnostic approach to functional validation,
supporting web (Puppeteer/Playwright), iOS (xc-mcp/simctl), CLI, and API testing.

The validation system follows a three-phase architecture:
1. Session 0 (Diagnostic): Detect project type, generate validation_config.json
2. Build Phase: Compilation and dependency validation
3. Functional Phase: End-user perspective testing with appropriate MCP tools

Usage:
    from ralph_orchestrator.validation import ValidationConfig, create_validation_gate

    # Load config (generated by DIAGNOSTIC_PROMPT.md)
    config = ValidationConfig.from_file("validation_config.json")

    # Create appropriate gate based on project type
    gate = create_validation_gate(config)

    # Execute validation
    result = await gate.validate(context)
"""

from .config import ValidationConfig, ValidationGateConfig
from .base import ValidationGate, ValidationResult
from .gates import (
    WebValidationGate,
    iOSValidationGate,
    CLIValidationGate,
    APIValidationGate,
    create_validation_gate,
)

__all__ = [
    "ValidationConfig",
    "ValidationGateConfig",
    "ValidationGate",
    "ValidationResult",
    "WebValidationGate",
    "iOSValidationGate",
    "CLIValidationGate",
    "APIValidationGate",
    "create_validation_gate",
]
